name: "Build and push on release"
on:
  release:
    types: [published]
jobs:
  get_changes:
    name: Get changed folders/files
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          matrix: true
          files: |
            containers/*
  build_test:
    name: test build
    needs: get_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJSON(needs.get_changes.outputs.all_changed_files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Split folder name
        env:
          FOLDER: ${{ matrix.folder }}
        id: split
        run: echo "fragment=${FOLDER##*/}" >> "${GITHUB_OUTPUT}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: schizo99/${{ steps.split.outputs.fragment }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          file: ./${{ matrix.folder }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}